---
jobs:
  - job: tests
    trigger: pull_request
    branch: main
    targets:
      - fedora-rawhide
      - fedora-stable
      - centos-stream-10-x86_64
    skip_build: true
    tf_extra_params:
      test:
        tmt:
          name: "/Plans/ci"
      environments:
        - tmt:
            context:
              target_PR_branch: main
